// src/app.content.tsx
import { t, type Dictionary } from "intlayer";

const appContent: Dictionary = {
    key: "app",
    content: {
        title: t({
            en: "My Todo App",
            tr: "Yapılacaklar Listem",
            de: "Meine Aufgabenliste",
            fr: "Mon application de tâches",
            es: "Mi aplicación de tareas",
            it: "La mia app delle cose da fare",
            ar: "تطبيقي للمهام",
            ru: "Мое приложение задач",
            zh: "我的待办应用",
            ja: "私のToDoアプリ",
            pt: "Meu aplicativo de tarefas",
            nl: "Mijn taken-app",
            ko: "나의 할 일 앱",
            fa: "برنامه کارهای من",
            hi: "मेरा टूडू ऐप"
        }),
        addTodo: t({
            en: "Add a new todo...",
            tr: "Yeni görev ekle...",
            de: "Neue Aufgabe hinzufügen...",
            fr: "Ajouter une nouvelle tâche...",
            es: "Agregar una nueva tarea...",
            it: "Aggiungi una nuova attività...",
            ar: "أضف مهمة جديدة...",
            ru: "Добавить новую задачу...",
            zh: "添加新待办...",
            ja: "新しいタスクを追加...",
            pt: "Adicionar uma nova tarefa...",
            nl: "Nieuwe taak toevoegen...",
            ko: "새 할 일을 추가...",
            fa: "افزودن کار جدید...",
            hi: "नया कार्य जोड़ें..."
        }),
        addDescription: t({
            en: "Add a description (optional)...",
            tr: "Açıklama ekle (opsiyonel)...",
            de: "Beschreibung hinzufügen (optional)...",
            fr: "Ajouter une description (optionnel)...",
            es: "Agregar una descripción (opcional)...",
            it: "Aggiungi una descrizione (opzionale)...",
            ar: "أضف وصفًا (اختياري)...",
            ru: "Добавить описание (необязательно)...",
            zh: "添加描述（可选）...",
            ja: "説明を追加（任意）...",
            pt: "Adicionar uma descrição (opcional)...",
            nl: "Beschrijving toevoegen (optioneel)...",
            ko: "설명 추가 (선택)...",
            fa: "افزودن توضیح (اختیاری)...",
            hi: "विवरण जोड़ें (वैकल्पिक)..."
        }),
        addButton: t({
            en: "Add",
            tr: "Ekle",
            de: "Hinzufügen",
            fr: "Ajouter",
            es: "Agregar",
            it: "Aggiungi",
            ar: "إضافة",
            ru: "Добавить",
            zh: "添加",
            ja: "追加",
            pt: "Adicionar",
            nl: "Toevoegen",
            ko: "추가",
            fa: "افزودن",
            hi: "जोड़ें"
        }),
        deleteButton: t({
            en: "Delete",
            tr: "Sil",
            de: "Löschen",
            fr: "Supprimer",
            es: "Eliminar",
            it: "Elimina",
            ar: "حذف",
            ru: "Удалить",
            zh: "删除",
            ja: "削除",
            pt: "Excluir",
            nl: "Verwijderen",
            ko: "삭제",
            fa: "حذف",
            hi: "हटाएं"
        }),
        darkMode: t({
            en: "Dark Mode",
            tr: "Karanlık Mod",
            de: "Dunkler Modus",
            fr: "Mode sombre",
            es: "Modo oscuro",
            it: "Modalità scura",
            ar: "الوضع الداكن",
            ru: "Темный режим",
            zh: "深色模式",
            ja: "ダークモード",
            pt: "Modo escuro",
            nl: "Donkere modus",
            ko: "다크 모드",
            fa: "حالت تاریک",
            hi: "डार्क मोड"
        }),
        lightMode: t({
            en: "Light Mode",
            tr: "Aydınlık Mod",
            de: "Heller Modus",
            fr: "Mode clair",
            es: "Modo claro",
            it: "Modalità chiara",
            ar: "الوضع الفاتح",
            ru: "Светлый режим",
            zh: "浅色模式",
            ja: "ライトモード",
            pt: "Modo claro",
            nl: "Lichte modus",
            ko: "라이트 모드",
            fa: "حالت روشن",
            hi: "लाइट मोड"
        }),
        searchPlaceholder: t({
            en: "Search todos...",
            tr: "Görevlerde ara...",
            de: "Aufgaben suchen...",
            fr: "Rechercher des tâches...",
            es: "Buscar tareas...",
            it: "Cerca attività...",
            ar: "ابحث في المهام...",
            ru: "Поиск задач...",
            zh: "搜索待办...",
            ja: "タスクを検索...",
            pt: "Pesquisar tarefas...",
            nl: "Taken zoeken...",
            ko: "할 일 검색...",
            fa: "جستجوی کارها...",
            hi: "कार्य खोजें..."
        }),
        emptyState: t({
            en: "No todos yet. Add a new one!",
            tr: "Henüz görev yok. Yeni bir görev ekleyin!",
            de: "Noch keine Aufgaben. Füge eine neue hinzu!",
            fr: "Aucune tâche pour l'instant. Ajoutez-en une nouvelle !",
            es: "Aún no hay tarefas. ¡Agrega una nueva!",
            it: "Nessuna attività ancora. Aggiungine una nuova!",
            ar: "لا توجد مهام بعد. أضف واحدة جديدة!",
            ru: "Пока нет задач. Добавьте новую!",
            zh: "还没有待办事项。添加一个新的吧！",
            ja: "まだタスクがありません。新しいタスクを追加しましょう！",
            pt: "Ainda não há tarefas. Adicione uma nova!",
            nl: "Nog geen taken. Voeg er een toe!",
            ko: "아직 할 일이 없습니다. 새로 추가하세요!",
            fa: "هنوز کاری وجود ندارد. یک کار جدید اضافه کنید!",
            hi: "अभी तक कोई कार्य नहीं है। एक नया जोड़ें!"
        }),
        work: t({
            en: "Work",
            tr: "İş",
            de: "Arbeit",
            fr: "Travail",
            es: "Trabajo",
            it: "Lavoro",
            ar: "عمل",
            ru: "Работа",
            zh: "工作",
            ja: "仕事",
            pt: "Trabalho",
            nl: "Werk",
            ko: "업무",
            fa: "کار",
            hi: "काम"
        }),
        school: t({
            en: "School",
            tr: "Okul",
            de: "Schule",
            fr: "École",
            es: "Escuela",
            it: "Scuola",
            ar: "مدرسة",
            ru: "Школа",
            zh: "学校",
            ja: "学校",
            pt: "Escola",
            nl: "School",
            ko: "학교",
            fa: "مدرسه",
            hi: "स्कूल"
        }),
        personal: t({
            en: "Personal",
            tr: "Kişisel",
            de: "Persönlich",
            fr: "Personnel",
            es: "Personal",
            it: "Personale",
            ar: "شخصي",
            ru: "Личное",
            zh: "个人",
            ja: "個人",
            pt: "Pessoal",
            nl: "Persoonlijk",
            ko: "개인",
            fa: "شخصی",
            hi: "व्यक्तिगत"
        }),
        all: t({
            en: "All",
            tr: "Tüm",
            de: "Alle",
            fr: "Tous",
            es: "Todos",
            it: "Tutti",
            ar: "الكل",
            ru: "Все",
            zh: "全部",
            ja: "すべて",
            pt: "Todos",
            nl: "Alles",
            ko: "전체",
            fa: "همه",
            hi: "सभी"
        }),
        dragToReorder: t({
            en: "Drag to reorder",
            tr: "Sürükleyerek sırala",
            de: "Zum Neuordnen ziehen",
            fr: "Glisser pour réorganiser",
            es: "Arrastrar para reordenar",
            it: "Trascina per riordinare",
            ar: "اسحب لإعادة الترتيب",
            ru: "Перетащите для изменения порядка",
            zh: "拖动以重新排序",
            ja: "ドラッグして並べ替え",
            pt: "Arraste para reordenar",
            nl: "Sleep om te herschikken",
            ko: "드래그하여 순서 변경",
            fa: "بکشید و مرتب‌سازی را تغییر دهید",
            hi: "ड्रैग करके क्रमबद्ध करें"
        }),
        noSort: t({
            en: "No Sort",
            tr: "Sıralama Yok",
            de: "Keine Sortierung",
            fr: "Aucun tri",
            es: "Sin orden",
            it: "Nessun ordinamento",
            ar: "بدون ترتيب",
            ru: "Без сортировки",
            zh: "不排序",
            ja: "並べ替えなし",
            pt: "Sem ordenação",
            nl: "Geen sortering",
            ko: "정렬 없음",
            fa: "بدون مرتب‌سازی",
            hi: "क्रमबद्ध नहीं"
        }),
        sortByName: t({
            en: "Sort by Name",
            tr: "İsme Göre Sırala",
            de: "Nach Name sortieren",
            fr: "Trier par nom",
            es: "Ordenar por nombre",
            it: "Ordina per nome",
            ar: "ترتيب حسب الاسم",
            ru: "Сортировать по имени",
            zh: "按名称排序",
            ja: "名前で並べ替え",
            pt: "Ordenar por nome",
            nl: "Sorteren op naam",
            ko: "이름순 정렬",
            fa: "بر اسم مرتب‌سازی",
            hi: "नाम के अनुसार क्रमबद्ध करें"
        }),
        sortByCategory: t({
            en: "Sort by Category",
            tr: "Kategoriye Göre Sırala",
            de: "Nach Kategorie sortieren",
            fr: "Trier par catégorie",
            es: "Ordenar por categoría",
            it: "Ordina per categoria",
            ar: "ترتيب حسب الفئة",
            ru: "Сортировать по категории",
            zh: "按类别排序",
            ja: "カテゴリで並べ替え",
            pt: "Ordenar por categoria",
            nl: "Sorteren op categorie",
            ko: "카테고리별 정렬",
            fa: "بر دسته مرتب‌سازی",
            hi: "श्रेणी के अनुसार क्रमबद्ध करें"
        }),
        sortByCompletion: t({
            en: "Sort by Status",
            tr: "Duruma Göre Sırala",
            de: "Nach Status sortieren",
            fr: "Trier par statut",
            es: "Ordenar por estado",
            it: "Ordina per stato",
            ar: "ترتيب حسب الحالة",
            ru: "Сортировать по статусу",
            zh: "按状态排序",
            ja: "ステータスで並べ替え",
            pt: "Ordenar por status",
            nl: "Sorteren op status",
            ko: "상태별 정렬",
            fa: "بر وضع مرتب‌سازی",
            hi: "अवस्था के अनुसार क्रमबद्ध करें"
        }),
        sortByDueDate: t({
            en: "Sort by Due Date",
            tr: "Bitiş Tarihine Göre Sırala",
            de: "Nach Fälligkeitsdatum sortieren",
            fr: "Trier par date d'échéance",
            es: "Ordenar por fecha de vencimiento",
            it: "Ordina per data di scadenza",
            ar: "ترتيب حسب تاريخ الاستحقاق",
            ru: "Сортировать по дате выполнения",
            zh: "按截止日期排序",
            ja: "期限で並べ替え",
            pt: "Ordenar por data de vencimento",
            nl: "Sorteren op vervaldatum",
            ko: "마감일순 정렬",
            fa: "بر تاریخ امروز مرتب‌سازی",
            hi: "अवधि के अनुसार क्रमबद्ध करें"
        }),
        todoText: t({
            en: "Todo text",
            tr: "Yapılacak iş",
            de: "Aufgabentext",
            fr: "Texte de la tâche",
            es: "Texto de la tarea",
            it: "Testo dell'attività",
            ar: "نص المهمة",
            ru: "Текст задачи",
            zh: "待办内容",
            ja: "タスク内容",
            pt: "Texto da tarefa",
            nl: "Taaktekst",
            ko: "할 일 내용",
            fa: "متن کار",
            hi: "कार्य विवरण"
        }),
        descriptionOptional: t({
            en: "Description (optional)",
            tr: "Açıklama (opsiyonel)",
            de: "Beschreibung (optional)",
            fr: "Description (optionnel)",
            es: "Descripción (opcional)",
            it: "Descrizione (opzionale)",
            ar: "وصف (اختياري)",
            ru: "Описание (необязательно)",
            zh: "描述（可选）",
            ja: "説明（任意）",
            pt: "Descrição (opcional)",
            nl: "Beschrijving (optioneel)",
            ko: "설명 (선택)",
            fa: "توضیح (اختیاری)",
            hi: "विवरण (वैकल्पिक)"
        }),
        save: t({
            en: "Save",
            tr: "Kaydet",
            de: "Speichern",
            fr: "Enregistrer",
            es: "Guardar",
            it: "Salva",
            ar: "حفظ",
            ru: "Сохранить",
            zh: "保存",
            ja: "保存",
            pt: "Salvar",
            nl: "Opslaan",
            ko: "저장",
            fa: "ذخیره کردن",
            hi: "सहेजें"
        }),
        cancel: t({
            en: "Cancel",
            tr: "İptal",
            de: "Abbrechen",
            fr: "Annuler",
            es: "Cancelar",
            it: "Annulla",
            ar: "إلغاء",
            ru: "Отмена",
            zh: "取消",
            ja: "キャンセル",
            pt: "Cancelar",
            nl: "Annuleren",
            ko: "취소",
            fa: "لغو",
            hi: "रद्द करें"
        }),
        priorityLow: t({
            en: "Low Priority",
            tr: "Düşük Öncelik",
            de: "Niedrige Priorität",
            fr: "Priorité basse",
            es: "Prioridad baja",
            it: "Bassa priorità",
            ar: "أولوية منخفضة",
            ru: "Низкий приоритет",
            zh: "低优先级",
            ja: "低優先度",
            pt: "Baixa prioridade",
            nl: "Lage prioriteit",
            ko: "낮은 우선순위",
            fa: "اولویه پایین",
            hi: "कम उपाध्यक्षता"
        }),
        priorityMedium: t({
            en: "Medium Priority",
            tr: "Orta Öncelik",
            de: "Mittlere Priorität",
            fr: "Priorité moyenne",
            es: "Prioridad media",
            it: "Media priorità",
            ar: "أولوية متوسطة",
            ru: "Средний приоритет",
            zh: "中优先级",
            ja: "中優先度",
            pt: "Média prioridade",
            nl: "Gemiddelde prioriteit",
            ko: "중간 우선순위",
            fa: "اولویه متوسطه",
            hi: "मध्यम उपाध्यक्षता"
        }),
        priorityHigh: t({
            en: "High Priority",
            tr: "Yüksek Öncelik",
            de: "Hohe Priorität",
            fr: "Priorité haute",
            es: "Prioridad alta",
            it: "Alta priorità",
            ar: "أولوية عالية",
            ru: "Высокий приоритет",
            zh: "高优先级",
            ja: "高優先度",
            pt: "Alta prioridade",
            nl: "Hoge prioriteit",
            ko: "높은 우선순위",
            fa: "اولویه بالا",
            hi: "उच्च उपाध्यक्षता"
        }),
        editTodo: t({
            en: "Edit todo",
            tr: "Düzenle",
            de: "Aufgabe bearbeiten",
            fr: "Modifier la tâche",
            es: "Editar tarea",
            it: "Modifica attività",
            ar: "تعديل المهمة",
            ru: "Редактировать задачу",
            zh: "编辑待办",
            ja: "タスクを編集",
            pt: "Editar tarefa",
            nl: "Taak bewerken",
            ko: "할 일 편집",
            fa: "ویرایش کار",
            hi: "कार्य संपादित करें"
        }),
        dueDate: t({
            en: "Due Date",
            tr: "Bitiş Tarihi",
            de: "Fälligkeitsdatum",
            fr: "Date d'échéance",
            es: "Fecha de vencimiento",
            it: "Data di scadenza",
            ar: "تاريخ الاستحقاق",
            ru: "Срок выполнения",
            zh: "截止日期",
            ja: "期限",
            pt: "Data de vencimento",
            nl: "Vervaldatum",
            ko: "마감일",
            fa: "تاریخ امروز",
            hi: "अवधि"
        }),
        selectDate: t({
            en: "Select date",
            tr: "Tarih seç",
            de: "Datum auswählen",
            fr: "Sélectionner une date",
            es: "Seleccionar fecha",
            it: "Seleziona data",
            ar: "اختر التاريخ",
            ru: "Выбрать дату",
            zh: "选择日期",
            ja: "日付を選択",
            pt: "Selecionar data",
            nl: "Selecteer datum",
            ko: "날짜 선택",
            fa: "تاریخ انتخاب کنید",
            hi: "तारीख चुनें"
        }),
        overdue: t({
            en: "Overdue",
            tr: "Süresi Geçmiş",
            de: "Überfällig",
            fr: "En retard",
            es: "Atrasado",
            it: "In ritardo",
            ar: "متأخر",
            ru: "Просрочено",
            zh: "已逾期",
            ja: "期限切れ",
            pt: "Atrasado",
            nl: "Te laat",
            ko: "기한 초과",
            fa: "مهلت گذشته",
            hi: "अवधि से अधिक"
        }),
        showSubtasks: t({
            en: "Show Subtasks",
            tr: "Alt Görevleri Göster",
            de: "Unteraufgaben anzeigen",
            fr: "Afficher les sous-tâches",
            es: "Mostrar subtareas",
            it: "Mostra sotto-attività",
            ar: "عرض المهام الفرعية",
            ru: "Показать подзадачи",
            zh: "显示子任务",
            ja: "サブタスクを表示",
            pt: "Mostrar subtarefas",
            nl: "Subtaken tonen",
            ko: "하위 작업 표시",
            fa: "زیرکارها را نمایش دهید",
            hi: "उपकार दिखाएं"
        }),
        hideSubtasks: t({
            en: "Hide Subtasks",
            tr: "Alt Görevleri Gizle",
            de: "Unteraufgaben ausblenden",
            fr: "Masquer les sous-tâches",
            es: "Ocultar subtareas",
            it: "Nascondi sotto-attività",
            ar: "إخفاء المهام الفرعية",
            ru: "Скрыть подзадачи",
            zh: "隐藏子任务",
            ja: "サブタスクを非表示",
            pt: "Ocultar subtarefas",
            nl: "Subtaken verbergen",
            ko: "하위 작업 숨기기",
            fa: "زیرکارها را پنهان کنید",
            hi: "उपकार छिपाएं"
        }),
        addSubtask: t({
            en: "Add a subtask...",
            tr: "Alt görev ekle...",
            de: "Unteraufgabe hinzufügen...",
            fr: "Ajouter une sous-tâche...",
            es: "Agregar una subtarea...",
            it: "Aggiungi una sotto-attività...",
            ar: "أضف مهمة فرعية...",
            ru: "Добавить подзадачу...",
            zh: "添加子任务...",
            ja: "サブタスクを追加...",
            pt: "Adicionar subtarefa...",
            nl: "Subtaak toevoegen...",
            ko: "하위 작업 추가...",
            fa: "زیرکاری اضافه کنید...",
            hi: "उपकार जोड़ें..."
        }),
        addSubtasks: t({
            en: "Add Subtasks",
            tr: "Alt Görev Ekle",
            de: "Unteraufgaben hinzufügen",
            fr: "Ajouter des sous-tâches",
            es: "Agregar subtareas",
            it: "Aggiungi sotto-attività",
            ar: "أضف مهام فرعية",
            ru: "Добавить подзадачи",
            zh: "添加子任务",
            ja: "サブタスクを追加",
            pt: "Adicionar subtarefas",
            nl: "Subtaken toevoegen",
            ko: "하위 작업 추가",
            fa: "زیرکارها را اضافه کنید",
            hi: "उपकार जोड़ें"
        }),
        subtaskText: t({
            en: "Subtask text",
            tr: "Alt görev metni",
            de: "Unteraufgabentext",
            fr: "Texte de la sous-tâche",
            es: "Texto de la subtarea",
            it: "Testo della sotto-attività",
            ar: "نص المهمة الفرعية",
            ru: "Текст подзадачи",
            zh: "子任务内容",
            ja: "サブタスク内容",
            pt: "Texto da subtarefa",
            nl: "Subtaaktekst",
            ko: "하위 작업 내용",
            fa: "متن زیرکاری",
            hi: "उपकार विवरण"
        }),
        noSubtasks: t({
            en: "No subtasks yet. Add one above!",
            tr: "Henüz alt görev yok. Yukarıdan ekleyin!",
            de: "Noch keine Unteraufgaben. Oben hinzufügen!",
            fr: "Aucune sous-tâche pour l'instant. Ajoutez-en une ci-dessus !",
            es: "Aún no hay subtareas. ¡Agrega una arriba!",
            it: "Nessuna sotto-attività ancora. Aggiungine una sopra!",
            ar: "لا توجد مهام فرعية بعد. أضف واحدة أعلاه!",
            ru: "Пока нет подзадач. Добавьте одну выше!",
            zh: "还没有子任务。请在上方添加！",
            ja: "まだサブタスクがありません。上で追加してください！",
            pt: "Ainda não há subtarefas. Adicione uma acima!",
            nl: "Nog geen subtaken. Voeg er hierboven een toe!",
            ko: "아직 하위 작업이 없습니다. 위에서 추가하세요!",
            fa: "هنوز زیرکاری وجود ندارد. یکی را بالا اضافه کنید!",
            hi: "अभी तक कोई उपकार नहीं है। ऊपर एक जोड़ें!"
        }),
        edit: t({
            en: "Edit",
            tr: "Düzenle",
            de: "Bearbeiten",
            fr: "Modifier",
            es: "Editar",
            it: "Modifica",
            ar: "تعديل",
            ru: "Редактировать",
            zh: "编辑",
            ja: "編集",
            pt: "Editar",
            nl: "Bewerken",
            ko: "편집",
            fa: "ویرایش",
            hi: "संपादित करें"
        }),
        delete: t({
            en: "Delete",
            tr: "Sil",
            de: "Löschen",
            fr: "Supprimer",
            es: "Eliminar",
            it: "Elimina",
            ar: "حذف",
            ru: "Удалить",
            zh: "删除",
            ja: "削除",
            pt: "Excluir",
            nl: "Verwijderen",
            ko: "삭제",
            fa: "حذف",
            hi: "हटाएं"
        }),
        add: t({
            en: "Add",
            tr: "Ekle",
            de: "Hinzufügen",
            fr: "Ajouter",
            es: "Agregar",
            it: "Aggiungi",
            ar: "إضافة",
            ru: "Добавить",
            zh: "添加",
            ja: "追加",
            pt: "Adicionar",
            nl: "Toevoegen",
            ko: "추가",
            fa: "اضافه کردن",
            hi: "जोड़ें"
        }),
        tags: t({
            en: "Tags",
            tr: "Etiketler",
            de: "Stichworte",
            fr: "Étiquettes",
            es: "Etiquetas",
            it: "Tag",
            ar: "وسوم",
            ru: "Теги",
            zh: "标签",
            ja: "タグ",
            pt: "Tags",
            nl: "Tags",
            ko: "태그",
            fa: "تگ‌ها",
            hi: "टैग"
        }),
        addTags: t({
            en: "Add tags",
            tr: "Etiket ekle",
            de: "Stichwort hinzufügen",
            fr: "Ajouter des étiquettes",
            es: "Agregar etiquetas",
            it: "Aggiungi tag",
            ar: "أضف وسوم",
            ru: "Добавить теги",
            zh: "添加标签",
            ja: "タグを追加",
            pt: "Adicionar tags",
            nl: "Tags toevoegen",
            ko: "태그 추가",
            fa: "تگ‌ها را اضافه کنید",
            hi: "टैग जोड़ें"
        }),
        filterByTag: t({
            en: "Filter by tag",
            tr: "Etikete göre filtrele",
            de: "Nach Stichwort filtern",
            fr: "Filtrer par étiquette",
            es: "Filtrar por etiqueta",
            it: "Filtra per tag",
            ar: "تصفية حسب الوسم",
            ru: "Фильтровать по тегу",
            zh: "按标签筛选",
            ja: "タグで絞り込む",
            pt: "Filtrar por tag",
            nl: "Filteren op tag",
            ko: "태그별 필터",
            fa: "بر تگ مرتب‌سازی",
            hi: "टैग के अनुसार फ़िल्टर करें"
        }),
        clearFilters: t({
            en: "Clear filters",
            tr: "Filtreleri temizle",
            de: "Filter löschen",
            fr: "Effacer les filtres",
            es: "Limpiar filtros",
            it: "Cancella filtri",
            ar: "مسح الفلاتر",
            ru: "Сбросить фильтры",
            zh: "清除筛选",
            ja: "フィルターをクリア",
            pt: "Limpar filtros",
            nl: "Filters wissen",
            ko: "필터 지우기",
            fa: "فیلترها را پاک کنید",
            hi: "फ़िल्टर साफ़ करें"
        }),
        pressEnterOrComma: t({
            en: "Press Enter or comma to add",
            tr: "Enter veya virgül tuşuna basarak ekleyin",
            de: "Drücken Sie Enter oder Komma zum Hinzufügen",
            fr: "Appuyez sur Entrée ou virgule pour ajouter",
            es: "Presione Enter o coma para agregar",
            it: "Premi Invio o virgola per aggiungere",
            ar: "اضغط Enter أو الفاصلة للإضافة",
            ru: "Нажмите Enter или запятую, чтобы добавить",
            zh: "按回车或逗号添加",
            ja: "Enterまたはカンマで追加",
            pt: "Pressione Enter ou vírgula para adicionar",
            nl: "Druk op Enter of komma om toe te voegen",
            ko: "Enter 또는 쉼표를 눌러 추가",
            fa: "Enter یا کاما را فشار دهید تا اضافه کنید",
            hi: "Enter या अंग्रेजी अक्षर जोड़ें"
        })
    }
} satisfies Dictionary;

export default appContent;